/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SignInWithGoogleRequest
 */
export interface SignInWithGoogleRequest {
  /**
   *
   * @type {string}
   * @memberof SignInWithGoogleRequest
   */
  idToken: string;
}

/**
 * Check if a given object implements the SignInWithGoogleRequest interface.
 */
export function instanceOfSignInWithGoogleRequest(value: object): value is SignInWithGoogleRequest {
  if (!("idToken" in value) || value["idToken"] === undefined) return false;
  return true;
}

export function SignInWithGoogleRequestFromJSON(json: any): SignInWithGoogleRequest {
  return SignInWithGoogleRequestFromJSONTyped(json, false);
}

export function SignInWithGoogleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInWithGoogleRequest {
  if (json == null) {
    return json;
  }
  return {
    idToken: json["idToken"],
  };
}

export function SignInWithGoogleRequestToJSON(json: any): SignInWithGoogleRequest {
  return SignInWithGoogleRequestToJSONTyped(json, false);
}

export function SignInWithGoogleRequestToJSONTyped(value?: SignInWithGoogleRequest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    idToken: value["idToken"],
  };
}
